
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "4UploadZ",
  description: "Generated by create next app",
};

export default function AuthLayout({ children }: { children: React.ReactNode }) {
  return (

          <>
            {children}
          </>

  );
}
